#
# -*- coding: utf-8; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-

language: python

python:
  - "2.7"

install:
  - pip install -r requirements-ci.txt

script:
  - rst2pdf full.rst > full.pdf
