#
# -*- coding: utf-8; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-

language: python

python:
  - "3.7"

install:
  - pip install -r requirements-ci.txt

script:
  - rst2pdf --config=./config.ini ./quick-eng.rst -o ./quick-eng.pdf
