#
# -*- coding: utf-8; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-

version: 2.1

workflows:
  post-merge:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            sudo pip install -r requirements.txt
      - run:
          name: Generate the pdf
          command: |
            rst2pdf --config=config.ini resume.rst -o resume.pdf
      - store_artifacts:
          path: resume.pdf
