#
# -*- coding: utf-8; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-

version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            sudo pip install -r requirements-ci.txt
      - run:
          name: Convert reStructuredText documents to PDF
          command: |
            rst2pdf --config=./config.ini ./brief.rst -o ./brief.pdf
      - store_artifacts:
          path: ./brief.pdf
